package Classes.Utils;
public enum TypeInst {
    PRINT    ,
    INITVAR  ,
    ASIGN    ,
    INITFUNC ,
    MAIN     ,
    PLUSC    ,
    MINUSC   ,
    MULTC    ,
    DIVC     ,
    MODC     ,
    BLOCK    ,
    IF       ,
    FOR      ,
    WHILE    ,
    DOWHILE  ,
    SWITCH   ,
    CASE     ,
    BREAK    ,
    CONTINUE ,
}