/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
/* 1. Package e importaciones */
package Language;
import java.util.ArrayList;
import Classes.Abstracts.*;
import Classes.Expressions.*;
import Classes.Instructions.*;
import Classes.Utils.IDValue;
import Classes.Utils.InitializeFor;
import Classes.Utils.Parameter;
import Classes.Utils.Type;
import Classes.Utils.TypeError;
import Classes.Utils.Outs;
public class Parser implements ParserConstants {
/* 2. Configuraciones para el analisis (Operaciones y Declaraciones) */
    public ArrayList<Instruction> execute;

  final public void parse() throws ParseException {
    INIT();
}

// INIT := INSTRUCTIONS EOF
  final public void INIT() throws ParseException {
    execute = INSTSGLOBAL();
    jj_consume_token(0);
}

// INSTSGLOBAL ::= INSTGLOBAL*
  final public ArrayList<Instruction> INSTSGLOBAL() throws ParseException {Instruction i;
    ArrayList<Instruction> l = new ArrayList<>();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case RW_main:
      case RW_void:
      case RW_String:
      case RW_boolean:
      case RW_char:
      case RW_int:
      case RW_double:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      try {
        i = INSTGLOBAL();
l.add(i);
      } catch (ParseException e) {
Token t = getNextToken();
            Outs.errors.add(Outs.newError(t.beginLine, t.beginColumn, TypeError.SYNTAX, "No se esperaba \"" + t.image + "\""));
            while(t.kind != TK_semicolon && t.kind != TK_rbrc && t != null && t.kind != EOF) {
                t = getNextToken();
            }
      }
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

/* INSTGLOBAL ::=
    CALLMAINFUNC |
    DECLID       |
    DECLFUNC     
*/
  final public Instruction INSTGLOBAL() throws ParseException {Instruction inst;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_main:{
      inst = CALLMAINFUNC();
{if ("" != null) return inst;}
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      if (jj_2_1(3)) {
        inst = DECLID();
{if ("" != null) return inst;}
      } else if (jj_2_2(3)) {
        inst = DECLFUNC();
{if ("" != null) return inst;}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

// CALLMAINFUNC ::= 'main' CALLFUNC ';'
  final public Instruction CALLMAINFUNC() throws ParseException {Token m;
    Expression callMain;
    m = jj_consume_token(RW_main);
    callMain = CALLFUNC();
    jj_consume_token(TK_semicolon);
{if ("" != null) return new MainMethod(m.beginLine, m.beginColumn, callMain);}
    throw new Error("Missing return statement in function");
}

// CALLFUNC ::= TK_id '(' LISTARGS ')'
  final public Expression CALLFUNC() throws ParseException {Token id;
    ArrayList<Expression> l;
    id = jj_consume_token(TK_id);
    jj_consume_token(TK_lpar);
    l = LISTARGS();
    jj_consume_token(TK_rpar);
{if ("" != null) return new CallFunction(id.beginLine, id.beginColumn, id.image, l);}
    throw new Error("Missing return statement in function");
}

// LISTARGS ::= (EXP (',' EXP)*)?
  final public ArrayList<Expression> LISTARGS() throws ParseException {Expression e1;
    ArrayList<Expression> l = new ArrayList<>();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_true:
    case RW_false:
    case TK_char:
    case TK_string:
    case TK_int:
    case TK_double:
    case TK_id:
    case TK_minus:
    case TK_not:
    case TK_lpar:{
      e1 = EXP();
l.add(e1);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TK_comma:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
        jj_consume_token(TK_comma);
        e1 = EXP();
l.add(e1);
      }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

// DECLID ::= TYPE INITIDS ';'
  final public Instruction DECLID() throws ParseException {Type t;
    ArrayList<IDValue> arr;
    t = TYPE();
    arr = INITIDS();
    jj_consume_token(TK_semicolon);
{if ("" != null) return new InitID(token.beginLine, token.beginColumn, arr, t);}
    throw new Error("Missing return statement in function");
}

// INITIDS ::= TK_id ('=' EXP)? (',' TK_id ('=' EXP)?)*
  final public ArrayList<IDValue> INITIDS() throws ParseException {Token id;
    Expression exp = null;
    ArrayList<IDValue> l = new ArrayList<>();
    id = jj_consume_token(TK_id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TK_equ:{
      jj_consume_token(TK_equ);
      exp = EXP();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
l.add(new IDValue(id.beginLine, id.beginColumn, id.image, exp));
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_comma:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_3;
      }
      jj_consume_token(TK_comma);
      id = jj_consume_token(TK_id);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_equ:{
        jj_consume_token(TK_equ);
        exp = EXP();
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        ;
      }
l.add(new IDValue(id.beginLine, id.beginColumn, id.image, exp));
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

/* DECLFUNC ::=
    TYPE   TK_id '(' LISTPARAMS ')' ENV |
    'void' TK_id '(' LISTPARAMS ')' ENV
*/
  final public Instruction DECLFUNC() throws ParseException {Token n;
    Type t;
    Token id;
    ArrayList<Parameter> l;
    Block b;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_String:
    case RW_boolean:
    case RW_char:
    case RW_int:
    case RW_double:{
      t = TYPE();
      id = jj_consume_token(TK_id);
      jj_consume_token(TK_lpar);
      l = LISTPARAMS();
      jj_consume_token(TK_rpar);
      b = ENV();
{if ("" != null) return new Function(id.beginLine, id.beginColumn, id.image, l, b, t);}
      break;
      }
    case RW_void:{
      n = jj_consume_token(RW_void);
      id = jj_consume_token(TK_id);
      jj_consume_token(TK_lpar);
      l = LISTPARAMS();
      jj_consume_token(TK_rpar);
      b = ENV();
{if ("" != null) return new Function(n.beginLine, n.beginColumn, id.image, l, b, Type.NULL);}
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// LISTPARAMS ::= (TYPE TK_id (',' TYPE TK_id)*)?
  final public ArrayList<Parameter> LISTPARAMS() throws ParseException {Type t;
    Token id;
    ArrayList<Parameter> l = new ArrayList<>();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_String:
    case RW_boolean:
    case RW_char:
    case RW_int:
    case RW_double:{
      t = TYPE();
      id = jj_consume_token(TK_id);
l.add(new Parameter(id.beginLine, id.beginColumn, id.image, t));
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TK_comma:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_4;
        }
        jj_consume_token(TK_comma);
        t = TYPE();
        id = jj_consume_token(TK_id);
l.add(new Parameter(id.beginLine, id.beginColumn, id.image, t));
      }
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

// IFSTRUCT ::= 'if' '(' EXP ')' ENV ('else' (IFSTRUCT | ENV))?
  final public Sentence IFSTRUCT() throws ParseException {Token r;
    Expression cn;
    Block b1;
    Sentence b2 = null;
    r = jj_consume_token(RW_if);
    jj_consume_token(TK_lpar);
    cn = EXP();
    jj_consume_token(TK_rpar);
    b1 = ENV();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_else:{
      jj_consume_token(RW_else);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case RW_if:{
        b2 = IFSTRUCT();
        break;
        }
      case TK_lbrc:{
        b2 = ENV();
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
{if ("" != null) return new If(r.beginLine, r.beginColumn, cn, b1, b2);}
    throw new Error("Missing return statement in function");
}

// SWITCHSTRUCT ::= 'switch' '(' EXP ')' ENVS
  final public Sentence SWITCHSTRUCT() throws ParseException {Token s;
    Expression exp;
    Object[] b;
    s = jj_consume_token(RW_switch);
    jj_consume_token(TK_lpar);
    exp = EXP();
    jj_consume_token(TK_rpar);
    b = ENVS();
{if ("" != null) return new Switch(s.beginLine, s.beginColumn, exp, (ArrayList<Case>) b[0], (Block) b[1]);}
    throw new Error("Missing return statement in function");
}

// ENVS ::= '{' CASESDEFAULT '}'
  final public Object[] ENVS() throws ParseException {Object[] casesdefault;
    jj_consume_token(TK_lbrc);
    casesdefault = CASESDEFAULT();
    jj_consume_token(TK_rbrc);
{if ("" != null) return casesdefault;}
    throw new Error("Missing return statement in function");
}

// CASESDEFAULT ::= (CASES)? (DEFAULT)?
  final public Object[] CASESDEFAULT() throws ParseException {ArrayList<Sentence> cases = null;
    Sentence default_ = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_case:{
      cases = CASES();
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_default:{
      default_ = DEFAULT();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
{if ("" != null) return new Object[] {cases, default_};}
    throw new Error("Missing return statement in function");
}

// CASES ::= (CASE)+
  final public ArrayList<Sentence> CASES() throws ParseException {Sentence c;
    ArrayList<Sentence> cases = new ArrayList<>();
    label_5:
    while (true) {
      c = CASE();
cases.add(c);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case RW_case:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
    }
{if ("" != null) return cases;}
    throw new Error("Missing return statement in function");
}

// CASE ::= 'case' EXP ':' (ENV | INSTRUCTIONS)
  final public Sentence CASE() throws ParseException {Token c;
    Block b;
    ArrayList<Sentence> i;
    Expression exp;
    Sentence case_;
    c = jj_consume_token(RW_case);
    exp = EXP();
    jj_consume_token(TK_colon);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TK_lbrc:{
      b = ENV();
case_ = new Case(c.beginLine, c.beginColumn, exp, b);
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      i = INSTRUCTIONS();
case_ = new Case(c.beginLine, c.beginColumn, exp, new Block(c.beginLine, c.beginColumn, i));
    }
{if ("" != null) return case_;}
    throw new Error("Missing return statement in function");
}

// DEFAULT ::= 'default' ':' (ENV | INSTRUCTIONS)
  final public Block DEFAULT() throws ParseException {Token d;
    Block b;
    ArrayList<Sentence> i;
    Block default_;
    d = jj_consume_token(RW_default);
    jj_consume_token(TK_colon);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TK_lbrc:{
      b = ENV();
default_ = b;
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      i = INSTRUCTIONS();
default_ = new Block(d.beginLine, d.beginColumn, i);
    }
{if ("" != null) return default_;}
    throw new Error("Missing return statement in function");
}

// LOOPFOR ::= 'for' '(' ARGSFOR ')' ENV
  final public Sentence LOOPFOR() throws ParseException {Token f;
    Object[] args;
    Block b;
    f = jj_consume_token(RW_for);
    jj_consume_token(TK_lpar);
    args = ARGSFOR();
    jj_consume_token(TK_rpar);
    b = ENV();
{if ("" != null) return new For(f.beginLine, f.beginColumn, (InitializeFor) args[0], (Expression) args[1], (ArrayList<Sentence>) args[2], b);}
    throw new Error("Missing return statement in function");
}

// ARGSFOR ::= (UPDATESFOR)? ';' (EXP)? ';' (UPDATESFOR)?
  final public Object[] ARGSFOR() throws ParseException {InitializeFor i = null;
    Expression e = null;
    ArrayList<Sentence> u = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_String:
    case RW_boolean:
    case RW_char:
    case RW_int:
    case RW_double:
    case TK_id:{
      i = INITIALIZEFOR();
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(TK_semicolon);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_true:
    case RW_false:
    case TK_char:
    case TK_string:
    case TK_int:
    case TK_double:
    case TK_id:
    case TK_minus:
    case TK_not:
    case TK_lpar:{
      e = EXP();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    jj_consume_token(TK_semicolon);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TK_id:{
      u = UPDATESFOR();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
{if ("" != null) return new Object[] {i, e, u};}
    throw new Error("Missing return statement in function");
}

/* INITIALIZEFOR ::=
    TYPE INITIDSFOR |
    REASIGNS        
*/
  final public InitializeFor INITIALIZEFOR() throws ParseException {Type t;
    ArrayList<IDValue> i;
    ArrayList<Instruction> r;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_String:
    case RW_boolean:
    case RW_char:
    case RW_int:
    case RW_double:{
      t = TYPE();
      i = INITIDSFOR();
{if ("" != null) return new InitializeFor(new InitID(i.get(0).line, i.get(0).column, i, t));}
      break;
      }
    case TK_id:{
      r = REASIGNS();
{if ("" != null) return new InitializeFor(r);}
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// INITIDSFOR ::= TK_id '=' EXP (',' TK_id '=' EXP)*
  final public ArrayList<IDValue> INITIDSFOR() throws ParseException {Token id;
    Expression exp;
    ArrayList<IDValue> l = new ArrayList<>();
    id = jj_consume_token(TK_id);
    jj_consume_token(TK_equ);
    exp = EXP();
l.add(new IDValue(id.beginLine, id.beginColumn, id.image, exp));
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_comma:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_6;
      }
      jj_consume_token(TK_comma);
      id = jj_consume_token(TK_id);
      jj_consume_token(TK_equ);
      exp = EXP();
l.add(new IDValue(id.beginLine, id.beginColumn, id.image, exp));
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

// REASIGNS ::= REASIGN (',' REASIGN)*
  final public ArrayList<Instruction> REASIGNS() throws ParseException {Instruction r;
    ArrayList<Instruction> l = new ArrayList<>();
    r = REASIGN();
l.add(r);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_comma:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_7;
      }
      jj_consume_token(TK_comma);
      r = REASIGN();
l.add(r);
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

// UPDATESFOR ::= UPDATEFOR (',' UPDATEFOR)*
  final public ArrayList<Sentence> UPDATESFOR() throws ParseException {Sentence up;
    ArrayList<Sentence> l = new ArrayList<>();
    up = UPDATEFOR();
l.add(up);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_comma:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_8;
      }
      jj_consume_token(TK_comma);
      up = UPDATEFOR();
l.add(up);
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

/* UPDATEFOR ::=
    INCDEC  |
    REASIGN |
    ADDSUB  
*/
  final public Sentence UPDATEFOR() throws ParseException {Sentence update;
    if (jj_2_3(2)) {
      update = INCDEC();
{if ("" != null) return update;}
    } else if (jj_2_4(2)) {
      update = REASIGN();
{if ("" != null) return update;}
    } else if (jj_2_5(2)) {
      update = ADDSUB();
{if ("" != null) return update;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// LOOPWHILE ::= 'while' '(' EXP ')' ENV
  final public Sentence LOOPWHILE() throws ParseException {Token w;
    Expression exp;
    Block b;
    w = jj_consume_token(RW_while);
    jj_consume_token(TK_lpar);
    exp = EXP();
    jj_consume_token(TK_rpar);
    b = ENV();
{if ("" != null) return new While(w.beginLine, w.beginColumn, exp, b);}
    throw new Error("Missing return statement in function");
}

// LOOPDOWHILE ::= 'do' ENV 'while' '(' EXP ')' ';'
  final public Sentence LOOPDOWHILE() throws ParseException {Token d;
    Block b;
    Expression exp;
    d = jj_consume_token(RW_do);
    b = ENV();
    jj_consume_token(RW_while);
    jj_consume_token(TK_lpar);
    exp = EXP();
    jj_consume_token(TK_rpar);
    jj_consume_token(TK_semicolon);
{if ("" != null) return new DoWhile(d.beginLine, d.beginColumn, exp, b);}
    throw new Error("Missing return statement in function");
}

// REASIGN ::= TK_id '=' EXP
  final public Instruction REASIGN() throws ParseException {Token id;
    Expression exp;
    id = jj_consume_token(TK_id);
    jj_consume_token(TK_equ);
    exp = EXP();
{if ("" != null) return new AsignID(id.beginLine, id.beginColumn, id.image, exp);}
    throw new Error("Missing return statement in function");
}

// INCDEC ::= TK_id ('++' | '--')
  final public Expression INCDEC() throws ParseException {Token id, s;
    id = jj_consume_token(TK_id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TK_inc:{
      s = jj_consume_token(TK_inc);
      break;
      }
    case TK_dec:{
      s = jj_consume_token(TK_dec);
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return new IncDec(id.beginLine, id.beginColumn, id.image, s.image);}
    throw new Error("Missing return statement in function");
}

// ADDSUB ::= TK_id ('+=' | '-=') EXP
  final public Instruction ADDSUB() throws ParseException {Token s;
    Token id;
    Expression exp;
    id = jj_consume_token(TK_id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TK_add:{
      s = jj_consume_token(TK_add);
      break;
      }
    case TK_sub:{
      s = jj_consume_token(TK_sub);
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    exp = EXP();
{if ("" != null) return new AddSub(id.beginLine, id.beginColumn, id.image, s.image, exp);}
    throw new Error("Missing return statement in function");
}

// CAST ::= TK_lpar TYPE TK_rpar EXP
  final public Expression CAST() throws ParseException {Token c;
    Type t;
    Expression exp;
    c = jj_consume_token(TK_lpar);
    t = TYPE();
    jj_consume_token(TK_rpar);
    exp = EXP();
{if ("" != null) return new Cast(c.beginLine, c.beginColumn, exp, t);}
    throw new Error("Missing return statement in function");
}

// PRINT ::= 'PRINT' '(' EXP? ')' ';'
  final public Instruction PRINT() throws ParseException {Token p;
    Expression exp = null;
    p = jj_consume_token(RW_print);
    jj_consume_token(TK_lpar);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_true:
    case RW_false:
    case TK_char:
    case TK_string:
    case TK_int:
    case TK_double:
    case TK_id:
    case TK_minus:
    case TK_not:
    case TK_lpar:{
      exp = EXP();
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    jj_consume_token(TK_rpar);
    jj_consume_token(TK_semicolon);
{if ("" != null) return new Print(p.beginLine, p.beginColumn, exp);}
    throw new Error("Missing return statement in function");
}

// ENV ::= '{' INSTRUCTIONS '}'
  final public Block ENV() throws ParseException {Token l;
    ArrayList<Sentence> ins;
    l = jj_consume_token(TK_lbrc);
    ins = INSTRUCTIONS();
    jj_consume_token(TK_rbrc);
{if ("" != null) return new Block(l.beginLine, l.beginColumn, ins);}
    throw new Error("Missing return statement in function");
}

// INSTRUCTIONS ::= INSTRUCTION*
  final public ArrayList<Sentence> INSTRUCTIONS() throws ParseException {Sentence i;
    ArrayList<Sentence> l = new ArrayList<>();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case RW_String:
      case RW_boolean:
      case RW_char:
      case RW_int:
      case RW_double:
      case RW_if:
      case RW_for:
      case RW_while:
      case RW_do:
      case RW_switch:
      case RW_break:
      case RW_continue:
      case RW_return:
      case RW_print:
      case TK_id:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_9;
      }
      try {
        i = INSTRUCTION();
l.add(i);
      } catch (ParseException e) {
Token t = getNextToken();
            Outs.errors.add(Outs.newError(t.beginLine, t.beginColumn, TypeError.SYNTAX, "No se esperaba \"" + t.image + "\""));
            while(t.kind != TK_semicolon && t.kind != TK_rbrc && t != null && t.kind != EOF) {
                t = getNextToken();
            }
      }
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

/* INSTRUCTION ::=
    DECLID              |
    IFSTRUCT            |
    SWITCHSTRUCT        |
    LOOPFOR             |
    LOOPWHILE           |
    LOOPDOWHILE         |
    REASIGN         ';' |
    ADDSUB          ';' |
    INCDEC          ';' |
    CALLFUNC        ';' |
    PRINT               |
    'return' (EXP)? ';' |
    'continue'      ';' |
    'break'         ';'
*/
  final public Sentence INSTRUCTION() throws ParseException {Sentence ins;
    Token trn;
    Expression exp = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_String:
    case RW_boolean:
    case RW_char:
    case RW_int:
    case RW_double:{
      ins = DECLID();
{if ("" != null) return ins;}
      break;
      }
    case RW_if:{
      ins = IFSTRUCT();
{if ("" != null) return ins;}
      break;
      }
    case RW_switch:{
      ins = SWITCHSTRUCT();
{if ("" != null) return ins;}
      break;
      }
    case RW_for:{
      ins = LOOPFOR();
{if ("" != null) return ins;}
      break;
      }
    case RW_while:{
      ins = LOOPWHILE();
{if ("" != null) return ins;}
      break;
      }
    case RW_do:{
      ins = LOOPDOWHILE();
{if ("" != null) return ins;}
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      if (jj_2_6(2)) {
        ins = REASIGN();
        jj_consume_token(TK_semicolon);
{if ("" != null) return ins;}
      } else if (jj_2_7(2)) {
        ins = ADDSUB();
        jj_consume_token(TK_semicolon);
{if ("" != null) return ins;}
      } else if (jj_2_8(2)) {
        ins = INCDEC();
        jj_consume_token(TK_semicolon);
{if ("" != null) return ins;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TK_id:{
          ins = CALLFUNC();
          jj_consume_token(TK_semicolon);
{if ("" != null) return ins;}
          break;
          }
        case RW_print:{
          ins = PRINT();
{if ("" != null) return ins;}
          break;
          }
        case RW_return:{
          trn = jj_consume_token(RW_return);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case RW_true:
          case RW_false:
          case TK_char:
          case TK_string:
          case TK_int:
          case TK_double:
          case TK_id:
          case TK_minus:
          case TK_not:
          case TK_lpar:{
            exp = EXP();
            break;
            }
          default:
            jj_la1[28] = jj_gen;
            ;
          }
          jj_consume_token(TK_semicolon);
{if ("" != null) return new Return(trn.beginLine, trn.beginColumn, exp);}
          break;
          }
        case RW_continue:{
          trn = jj_consume_token(RW_continue);
          jj_consume_token(TK_semicolon);
{if ("" != null) return new Continue(trn.beginLine, trn.beginColumn);}
          break;
          }
        case RW_break:{
          trn = jj_consume_token(RW_break);
          jj_consume_token(TK_semicolon);
{if ("" != null) return new Break(trn.beginLine, trn.beginColumn);}
          break;
          }
        default:
          jj_la1[30] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

/* TYPE ::=
    RW_String  |
    RW_int     |
    RW_boolean |
    RW_char    |
    RW_double  
*/
  final public Type TYPE() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RW_String:{
      jj_consume_token(RW_String);
{if ("" != null) return Type.STRING;}
      break;
      }
    case RW_int:{
      jj_consume_token(RW_int);
{if ("" != null) return Type.INT;}
      break;
      }
    case RW_boolean:{
      jj_consume_token(RW_boolean);
{if ("" != null) return Type.BOOLEAN;}
      break;
      }
    case RW_char:{
      jj_consume_token(RW_char);
{if ("" != null) return Type.CHAR;}
      break;
      }
    case RW_double:{
      jj_consume_token(RW_double);
{if ("" != null) return Type.DOUBLE;}
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// EXP ::= opOr ('?' opOr ':' opOr)?
  final public Expression EXP() throws ParseException {Expression c, y, n;
    c = opOr();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TK_question:{
      jj_consume_token(TK_question);
      y = opOr();
      jj_consume_token(TK_colon);
      n = opOr();
c = new Ternary(c.line, c.column, c, y, n);
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      ;
    }
{if ("" != null) return c;}
    throw new Error("Missing return statement in function");
}

// opOr ::= opAnd ('||' opAnd)*
  final public Expression opOr() throws ParseException {Token s;
    Expression e1, e2;
    e1 = opAnd();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_or:{
        ;
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        break label_10;
      }
      s = jj_consume_token(TK_or);
      e2 = opAnd();
e1 = new Logic(s.beginLine, s.beginColumn, e1, s.image, e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

// opAnd ::= opEqu ('&&' opEqu)*
  final public Expression opAnd() throws ParseException {Token s;
    Expression e1, e2;
    e1 = opEqu();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_and:{
        ;
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        break label_11;
      }
      s = jj_consume_token(TK_and);
      e2 = opEqu();
e1 = new Logic(s.beginLine, s.beginColumn, e1, s.image, e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

/*opEqu ::=
    opCmp ('==' opCmp)* |
    opCmp ('!=' opCmp)* 
*/
  final public Expression opEqu() throws ParseException {Token s;
    Expression e1, e2;
    e1 = opCmp();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_equequ:
      case TK_notequ:{
        ;
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_equequ:{
        s = jj_consume_token(TK_equequ);
        e2 = opCmp();
e1 = new Relational(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      case TK_notequ:{
        s = jj_consume_token(TK_notequ);
        e2 = opCmp();
e1 = new Relational(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

/* opCmp ::=
    opAdd ('<=' opAdd)* |
    opAdd ('>=' opAdd)* |
    opAdd ('<' opAdd)*  |
    opAdd ('>' opAdd)*  
*/
  final public Expression opCmp() throws ParseException {Token s;
    Expression e1, e2;
    e1 = opAdd();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_lessequ:
      case TK_moreequ:
      case TK_less:
      case TK_more:{
        ;
        break;
        }
      default:
        jj_la1[37] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_lessequ:{
        s = jj_consume_token(TK_lessequ);
        e2 = opAdd();
e1 = new Relational(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      case TK_moreequ:{
        s = jj_consume_token(TK_moreequ);
        e2 = opAdd();
e1 = new Relational(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      case TK_less:{
        s = jj_consume_token(TK_less);
        e2 = opAdd();
e1 = new Relational(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      case TK_more:{
        s = jj_consume_token(TK_more);
        e2 = opAdd();
e1 = new Relational(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

/* opAdd ::=
    opMult ('+' opMult)* |
    opMult ('-' opMult)* 
*/
  final public Expression opAdd() throws ParseException {Token s;
    Expression e1, e2;
    e1 = opMult();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_plus:
      case TK_minus:{
        ;
        break;
        }
      default:
        jj_la1[39] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_plus:{
        s = jj_consume_token(TK_plus);
        e2 = opMult();
e1 = new Arithmetic(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      case TK_minus:{
        s = jj_consume_token(TK_minus);
        e2 = opMult();
e1 = new Arithmetic(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

/* opMult ::=
    unary ('*' unary)* |
    unary ('/' unary)* 
*/
  final public Expression opMult() throws ParseException {Token s;
    Expression e1, e2;
    e1 = unary();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_mult:
      case TK_div:
      case TK_mod:{
        ;
        break;
        }
      default:
        jj_la1[41] = jj_gen;
        break label_15;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_mult:{
        s = jj_consume_token(TK_mult);
        e2 = unary();
e1 = new Arithmetic(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      case TK_div:{
        s = jj_consume_token(TK_div);
        e2 = unary();
e1 = new Arithmetic(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      case TK_mod:{
        s = jj_consume_token(TK_mod);
        e2 = unary();
e1 = new Arithmetic(e1.line, e1.column, e1, s.image, e2);
        break;
        }
      default:
        jj_la1[42] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

/* unary ::=
    '-' unary |
    '!' unary |
    primitive 
*/
  final public Expression unary() throws ParseException {Token s;
    Expression exp;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TK_minus:{
      s = jj_consume_token(TK_minus);
      exp = unary();
{if ("" != null) return new Arithmetic(s.beginLine, s.beginColumn, null, s.image, exp);}
      break;
      }
    case TK_not:{
      s = jj_consume_token(TK_not);
      exp = unary();
{if ("" != null) return new Logic(s.beginLine, s.beginColumn, null, s.image, exp);}
      break;
      }
    case RW_true:
    case RW_false:
    case TK_char:
    case TK_string:
    case TK_int:
    case TK_double:
    case TK_id:
    case TK_lpar:{
      exp = primitive();
{if ("" != null) return exp;}
      break;
      }
    default:
      jj_la1[43] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

/* primitive ::=
    INCDEC      |
    CALLFUNC    |
    TK_id       |
    TK_string   |
    TK_char     |
    TK_int      |
    TK_double   |
    RW_true     |
    RW_false    |
    '(' EXP ')' 
*/
  final public Expression primitive() throws ParseException {Token p;
    Expression exp;
    if (jj_2_9(2)) {
      exp = INCDEC();
{if ("" != null) return exp;}
    } else if (jj_2_10(2)) {
      exp = CALLFUNC();
{if ("" != null) return exp;}
    } else if (jj_2_11(4)) {
      exp = CAST();
{if ("" != null) return exp;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TK_id:{
        p = jj_consume_token(TK_id);
{if ("" != null) return new AccessID(p.beginLine, p.beginColumn, p.image);}
        break;
        }
      case TK_string:{
        p = jj_consume_token(TK_string);
{if ("" != null) return new Primitive(p.beginLine, p.beginColumn, p.image.substring(1, p.image.length() - 1), Type.STRING);}
        break;
        }
      case TK_char:{
        p = jj_consume_token(TK_char);
{if ("" != null) return new Primitive(p.beginLine, p.beginColumn, p.image.substring(1, p.image.length() - 1), Type.CHAR);}
        break;
        }
      case TK_int:{
        p = jj_consume_token(TK_int);
{if ("" != null) return new Primitive(p.beginLine, p.beginColumn, p.image, Type.INT);}
        break;
        }
      case TK_double:{
        p = jj_consume_token(TK_double);
{if ("" != null) return new Primitive(p.beginLine, p.beginColumn, p.image, Type.DOUBLE);}
        break;
        }
      case RW_true:{
        p = jj_consume_token(RW_true);
{if ("" != null) return new Primitive(p.beginLine, p.beginColumn, p.image, Type.BOOLEAN);}
        break;
        }
      case RW_false:{
        p = jj_consume_token(RW_false);
{if ("" != null) return new Primitive(p.beginLine, p.beginColumn, p.image, Type.BOOLEAN);}
        break;
        }
      case TK_lpar:{
        jj_consume_token(TK_lpar);
        exp = EXP();
        jj_consume_token(TK_rpar);
{if ("" != null) return exp;}
        break;
        }
      default:
        jj_la1[44] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_3_3()
 {
    if (jj_3R_INCDEC_405_5_18()) return true;
    return false;
  }

  private boolean jj_3R_opCmp_557_5_38()
 {
    if (jj_3R_opAdd_572_5_39()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_DECLFUNC_228_5_17()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_DECLID_204_5_16()) return true;
    return false;
  }

  private boolean jj_3R_opEqu_542_5_37()
 {
    if (jj_3R_opCmp_557_5_38()) return true;
    return false;
  }

  private boolean jj_3R_primitive_630_5_53()
 {
    if (jj_scan_token(TK_lpar)) return true;
    return false;
  }

  private boolean jj_3R_primitive_629_5_52()
 {
    if (jj_scan_token(RW_false)) return true;
    return false;
  }

  private boolean jj_3R_primitive_628_5_51()
 {
    if (jj_scan_token(RW_true)) return true;
    return false;
  }

  private boolean jj_3R_primitive_627_5_50()
 {
    if (jj_scan_token(TK_double)) return true;
    return false;
  }

  private boolean jj_3R_primitive_626_5_49()
 {
    if (jj_scan_token(TK_int)) return true;
    return false;
  }

  private boolean jj_3R_primitive_625_5_48()
 {
    if (jj_scan_token(TK_char)) return true;
    return false;
  }

  private boolean jj_3R_opAnd_530_5_36()
 {
    if (jj_3R_opEqu_542_5_37()) return true;
    return false;
  }

  private boolean jj_3R_primitive_624_5_47()
 {
    if (jj_scan_token(TK_string)) return true;
    return false;
  }

  private boolean jj_3R_primitive_623_5_46()
 {
    if (jj_scan_token(TK_id)) return true;
    return false;
  }

  private boolean jj_3_11()
 {
    if (jj_3R_CAST_424_5_22()) return true;
    return false;
  }

  private boolean jj_3_10()
 {
    if (jj_3R_CALLFUNC_185_5_21()) return true;
    return false;
  }

  private boolean jj_3R_primitive_620_5_45()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3R_primitive_623_5_46()) {
    jj_scanpos = xsp;
    if (jj_3R_primitive_624_5_47()) {
    jj_scanpos = xsp;
    if (jj_3R_primitive_625_5_48()) {
    jj_scanpos = xsp;
    if (jj_3R_primitive_626_5_49()) {
    jj_scanpos = xsp;
    if (jj_3R_primitive_627_5_50()) {
    jj_scanpos = xsp;
    if (jj_3R_primitive_628_5_51()) {
    jj_scanpos = xsp;
    if (jj_3R_primitive_629_5_52()) {
    jj_scanpos = xsp;
    if (jj_3R_primitive_630_5_53()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_3R_INCDEC_405_5_18()) return true;
    return false;
  }

  private boolean jj_3R_opOr_521_5_35()
 {
    if (jj_3R_opAnd_530_5_36()) return true;
    return false;
  }

  private boolean jj_3R_CAST_424_5_22()
 {
    if (jj_scan_token(TK_lpar)) return true;
    if (jj_3R_TYPE_501_5_23()) return true;
    if (jj_scan_token(TK_rpar)) return true;
    if (jj_3R_EXP_511_5_27()) return true;
    return false;
  }

  private boolean jj_3R_DECLFUNC_229_5_26()
 {
    if (jj_scan_token(RW_void)) return true;
    if (jj_scan_token(TK_id)) return true;
    if (jj_scan_token(TK_lpar)) return true;
    return false;
  }

  private boolean jj_3R_DECLFUNC_228_5_17()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_DECLFUNC_228_5_25()) {
    jj_scanpos = xsp;
    if (jj_3R_DECLFUNC_229_5_26()) return true;
    }
    return false;
  }

  private boolean jj_3R_DECLFUNC_228_5_25()
 {
    if (jj_3R_TYPE_501_5_23()) return true;
    if (jj_scan_token(TK_id)) return true;
    if (jj_scan_token(TK_lpar)) return true;
    return false;
  }

  private boolean jj_3R_INITIDS_212_19_33()
 {
    if (jj_scan_token(TK_equ)) return true;
    return false;
  }

  private boolean jj_3R_ADDSUB_416_5_20()
 {
    if (jj_scan_token(TK_id)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) return true;
    }
    return false;
  }

  private boolean jj_3R_EXP_511_5_27()
 {
    if (jj_3R_opOr_521_5_35()) return true;
    return false;
  }

  private boolean jj_3R_unary_602_5_44()
 {
    if (jj_3R_primitive_620_5_45()) return true;
    return false;
  }

  private boolean jj_3R_unary_601_5_43()
 {
    if (jj_scan_token(TK_not)) return true;
    return false;
  }

  private boolean jj_3R_unary_600_5_42()
 {
    if (jj_scan_token(TK_minus)) return true;
    return false;
  }

  private boolean jj_3R_unary_600_5_41()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_unary_600_5_42()) {
    jj_scanpos = xsp;
    if (jj_3R_unary_601_5_43()) {
    jj_scanpos = xsp;
    if (jj_3R_unary_602_5_44()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_TYPE_505_5_32()
 {
    if (jj_scan_token(RW_double)) return true;
    return false;
  }

  private boolean jj_3R_TYPE_504_5_31()
 {
    if (jj_scan_token(RW_char)) return true;
    return false;
  }

  private boolean jj_3R_INITIDS_214_9_34()
 {
    if (jj_scan_token(TK_comma)) return true;
    return false;
  }

  private boolean jj_3R_TYPE_503_5_30()
 {
    if (jj_scan_token(RW_boolean)) return true;
    return false;
  }

  private boolean jj_3R_TYPE_502_5_29()
 {
    if (jj_scan_token(RW_int)) return true;
    return false;
  }

  private boolean jj_3R_TYPE_501_5_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_TYPE_501_5_28()) {
    jj_scanpos = xsp;
    if (jj_3R_TYPE_502_5_29()) {
    jj_scanpos = xsp;
    if (jj_3R_TYPE_503_5_30()) {
    jj_scanpos = xsp;
    if (jj_3R_TYPE_504_5_31()) {
    jj_scanpos = xsp;
    if (jj_3R_TYPE_505_5_32()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_TYPE_501_5_28()
 {
    if (jj_scan_token(RW_String)) return true;
    return false;
  }

  private boolean jj_3R_INCDEC_405_5_18()
 {
    if (jj_scan_token(TK_id)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) return true;
    }
    return false;
  }

  private boolean jj_3R_INITIDS_212_5_24()
 {
    if (jj_scan_token(TK_id)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_INITIDS_212_19_33()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_INITIDS_214_9_34()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_REASIGN_399_5_19()
 {
    if (jj_scan_token(TK_id)) return true;
    if (jj_scan_token(TK_equ)) return true;
    return false;
  }

  private boolean jj_3R_opMult_585_5_40()
 {
    if (jj_3R_unary_600_5_41()) return true;
    return false;
  }

  private boolean jj_3R_DECLID_204_5_16()
 {
    if (jj_3R_TYPE_501_5_23()) return true;
    if (jj_3R_INITIDS_212_5_24()) return true;
    if (jj_scan_token(TK_semicolon)) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_3R_INCDEC_405_5_18()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_ADDSUB_416_5_20()) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_REASIGN_399_5_19()) return true;
    return false;
  }

  private boolean jj_3R_opAdd_572_5_39()
 {
    if (jj_3R_opMult_585_5_40()) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_ADDSUB_416_5_20()) return true;
    return false;
  }

  private boolean jj_3R_CALLFUNC_185_5_21()
 {
    if (jj_scan_token(TK_id)) return true;
    if (jj_scan_token(TK_lpar)) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_REASIGN_399_5_19()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[45];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xfe,0x2,0x0,0x7d80000,0x0,0x0,0x0,0xfc,0x0,0xf8,0x100,0x200,0x4000,0x8000,0x4000,0x0,0x0,0x40000f8,0x7d80000,0x4000000,0x40000f8,0x0,0x0,0x0,0x18000000,0x60000000,0x7d80000,0x4273df8,0x7d80000,0x3df8,0x4270000,0xf8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80000000,0x80000000,0x0,0x0,0x7d80000,0x7d80000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x40000,0x6001,0x100,0x40000,0x100,0x0,0x40000,0x0,0x10000,0x0,0x0,0x0,0x0,0x10000,0x10000,0x0,0x6001,0x0,0x0,0x40000,0x40000,0x40000,0x0,0x0,0x6001,0x0,0x6001,0x0,0x0,0x0,0x200000,0x1000,0x800,0x30,0x30,0x6c0,0x6c0,0x1,0x1,0xe,0xe,0x6001,0x4000,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[11];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[61];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 45; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 61; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 11; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
