/* Generated By:JavaCC: Do not edit this line. ParserFConstants.java */
/* 1. Package e importaciones */
package Language;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserFConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RW_main = 1;
  /** RegularExpression Id. */
  int RW_void = 2;
  /** RegularExpression Id. */
  int RW_String = 3;
  /** RegularExpression Id. */
  int RW_boolean = 4;
  /** RegularExpression Id. */
  int RW_char = 5;
  /** RegularExpression Id. */
  int RW_int = 6;
  /** RegularExpression Id. */
  int RW_double = 7;
  /** RegularExpression Id. */
  int RW_if = 8;
  /** RegularExpression Id. */
  int RW_else = 9;
  /** RegularExpression Id. */
  int RW_for = 10;
  /** RegularExpression Id. */
  int RW_while = 11;
  /** RegularExpression Id. */
  int RW_do = 12;
  /** RegularExpression Id. */
  int RW_switch = 13;
  /** RegularExpression Id. */
  int RW_case = 14;
  /** RegularExpression Id. */
  int RW_default = 15;
  /** RegularExpression Id. */
  int RW_break = 16;
  /** RegularExpression Id. */
  int RW_continue = 17;
  /** RegularExpression Id. */
  int RW_return = 18;
  /** RegularExpression Id. */
  int RW_true = 19;
  /** RegularExpression Id. */
  int RW_false = 20;
  /** RegularExpression Id. */
  int RW_print = 21;
  /** RegularExpression Id. */
  int TK_char = 22;
  /** RegularExpression Id. */
  int TK_string = 23;
  /** RegularExpression Id. */
  int TK_int = 24;
  /** RegularExpression Id. */
  int TK_double = 25;
  /** RegularExpression Id. */
  int TK_id = 26;
  /** RegularExpression Id. */
  int TK_inc = 27;
  /** RegularExpression Id. */
  int TK_dec = 28;
  /** RegularExpression Id. */
  int TK_add = 29;
  /** RegularExpression Id. */
  int TK_sub = 30;
  /** RegularExpression Id. */
  int TK_plus = 31;
  /** RegularExpression Id. */
  int TK_minus = 32;
  /** RegularExpression Id. */
  int TK_mult = 33;
  /** RegularExpression Id. */
  int TK_div = 34;
  /** RegularExpression Id. */
  int TK_mod = 35;
  /** RegularExpression Id. */
  int TK_equequ = 36;
  /** RegularExpression Id. */
  int TK_notequ = 37;
  /** RegularExpression Id. */
  int TK_lessequ = 38;
  /** RegularExpression Id. */
  int TK_moreequ = 39;
  /** RegularExpression Id. */
  int TK_equ = 40;
  /** RegularExpression Id. */
  int TK_less = 41;
  /** RegularExpression Id. */
  int TK_more = 42;
  /** RegularExpression Id. */
  int TK_and = 43;
  /** RegularExpression Id. */
  int TK_or = 44;
  /** RegularExpression Id. */
  int TK_not = 45;
  /** RegularExpression Id. */
  int TK_lpar = 46;
  /** RegularExpression Id. */
  int TK_rpar = 47;
  /** RegularExpression Id. */
  int TK_lbrc = 48;
  /** RegularExpression Id. */
  int TK_rbrc = 49;
  /** RegularExpression Id. */
  int TK_comma = 50;
  /** RegularExpression Id. */
  int TK_colon = 51;
  /** RegularExpression Id. */
  int TK_semicolon = 52;
  /** RegularExpression Id. */
  int TK_question = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"main\"",
    "\"void\"",
    "\"String\"",
    "\"boolean\"",
    "\"char\"",
    "\"int\"",
    "\"double\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"print\"",
    "<TK_char>",
    "<TK_string>",
    "<TK_int>",
    "<TK_double>",
    "<TK_id>",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"?\"",
    "\"\\n\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 58>",
    "<token of kind 59>",
    "<token of kind 60>",
  };

}
